
columns:

 longitude: float
 latitude: float
 housing_median_age: float
 total_rooms: float64
 total_bedrooms: float64
 population: float64
 households: float64
 median_income: float64
 median_house_value: float64
 ocean_proximity: object


target_column: median_house_value

domain_value:
 ocean_proximity:
  - <1H OCEAN 
  - INLAND 
  - ISLAND
  - NEAR BAY
  - NEAR OCEAN 
